#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in6,    lineLeft,       sensorLineFollower)
#pragma config(Sensor, in7,    lineCenter,     sensorLineFollower)
#pragma config(Sensor, in8,    lineRight,      sensorLineFollower)
#pragma config(Sensor, dgtl1,  piston,         sensorDigitalOut)
#pragma config(Sensor, dgtl9,  sonar,          sensorSONAR_cm)
#pragma config(Sensor, dgtl11, bumperSwitch,   sensorNone)
#pragma config(Sensor, dgtl12, limitSwitch,    sensorDigitalIn)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           motorLeft,     tmotorVex393_MC29, openLoop, reversed, driveLeft, encoderPort, I2C_1)
#pragma config(Motor,  port3,           motorRight,    tmotorVex393_MC29, openLoop, driveRight, encoderPort, I2C_2)
#pragma config(Motor,  port10,          motorNoEnc,    tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int nullZone(int x, int range){
	if(abs(x)<range)
		return 0;
	return x;
}

int joystickNullZone = 15;

task main()
{
	while(1){
		double potVal = SensorValue[potentiometer];

		int distance = SensorValue[sonar];

		int lineLeftValue   = SensorValue[lineLeft];
		int lineCenterValue = SensorValue[lineLeft];
		int lineRightValue  = SensorValue[lineLeft];

		bool bumperVal = SensorValue[bumperSwitch];

		bool limitVal  = SensorValue[limitSwitch];


		double motorSpeed = potVal/4095 * 255 -127;
		int x = motorSpeed;
		motor[motorNoEnc] = nullZone(x, joystickNullZone);

		motor[motorLeft]  = nullZone(vexRT[Ch3], joystickNullZone);
		motor[motorRight] = nullZone(vexRT[Ch2], joystickNullZone);

		long encoderLeft  = SensorValue[I2C_1];
		long encoderRight = SensorValue[I2C_2];
	}
}
